:managers:
  - "localhost:10020" # master
  - "localhost:10021" # slave
:credential:
  :access_key_id: "05236"
  :secret_access_key: "802562235"
:session:
  :local:
    :secret: ""
    :expire_after: 300
:snmp:
  - ETS memory usage (1-min Averages)
  - Processes memory usage (1-min Averages)
  - System memory usage (1-min Averages)
:plugins:
#  - "disable_sign_up.rb"
